from typing import Literal
from pydantic import BaseModel, Field


class PracticeGenerateRequest(BaseModel):
    """Request payload for generating a dynamic practice session."""
    lesson_id: int = Field(..., description="ID of the lesson to derive grammar context from.")
    theme: str = Field(..., description="The user's selected theme (e.g. Cinema, Music, Job Interviews).")


class ExerciseItemSchema(BaseModel):
    """Schema representing a single dynamically generated practice exercise."""
    id: int = Field(..., description="1-based index of the exercise.")
    type: Literal["fill_in_the_blank", "roleplay_response"] = Field(
        ..., description="The exercise type: fill_in_the_blank or roleplay_response."
    )
    prompt: str = Field(..., description="The prompt or conversation line shown to the user in English.")
    correct_answer: str = Field(..., description="The exact correct answer targeted in English.")
    hint: str = Field(..., description="A brief grammatical hint or clue in Spanish.")


class PracticeSessionResponseSchema(BaseModel):
    """Full schema representing the complete dynamic practice session generated by Ollama."""
    session_id: str = Field(..., description="Unique UUID identifier for this session.")
    theme: str = Field(..., description="The theme utilized in the session generation.")
    grammar_focus: str = Field(..., description="Grammar topic and CEFR level context.")
    exercises: list[ExerciseItemSchema] = Field(default=[], description="List of generated exercises.")
    is_rejected: bool = Field(default=False, description="Flag indicating if the theme was rejected for being vulgar/illegal.")
    rejection_reason: str | None = Field(default=None, description="Explanation in Spanish of why the theme was rejected.")
